# -*- coding: utf-8 -*-
"""
Nature Cities | Main Fig. 1 compositor v4-return with B tweak and two-figure C
--------------------------------------------------
This version addresses the requested issues:

1. Panel letters in the right column are aligned consistently.
2. Panel a is drawn directly from data rather than embedded as a PNG, so the
   legend can be placed in a reserved blank area instead of covering the map.
3. Panel b uses a single conventional fixed buffer with a question mark to
   show uncertain/ambiguous radius selection; footprint diagrams are smaller
   and no longer overlap.
4. Panel c is redesigned:
       left: compact 3-sector-to-2-sector aggregation sketch
       right: final upper-semicircle 2 × 7 sector-grid
   The wind-direction arrow no longer overlaps the 14-cell summary.
5. Panel d is revised to match the manuscript logic:
       spatial/temporal CV + SHAP attribution,
   rather than only "Spatial CV model". The unnecessary output sentence is
   removed, and the bottom row is aligned directly under the workflow boxes.

Run:
    python code/scripts/reproduce_fig1_from_source_data.py
"""

from __future__ import annotations

import os
import time
import math
import warnings
from typing import Optional, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.lines as mlines
from matplotlib.gridspec import GridSpec
from matplotlib.patches import Circle, Wedge, Rectangle, FancyArrowPatch, Polygon, Arc
from matplotlib import patheffects as pe
from shapely.geometry import LineString

try:
    import geopandas as gpd
    GEOPANDAS_AVAILABLE = True
except Exception:
    GEOPANDAS_AVAILABLE = False

warnings.filterwarnings("ignore")


# =============================================================================
# 1. USER CONFIGURATION
# =============================================================================

# Repository-relative input/output paths for the public release package.
# The source-data files are generated by code/scripts/prepare_fig1_source_data_052314.py.
def find_repo_root() -> str:
    this_dir = os.path.dirname(os.path.abspath(__file__))
    return os.path.abspath(os.path.join(this_dir, "..", ".."))


REPO_ROOT = find_repo_root()
FIG1_SOURCE_DIR = os.path.join(REPO_ROOT, "data", "source_data", "main", "Fig1")

MONITORING_SITES_FILE = os.path.join(FIG1_SOURCE_DIR, "monitoring_sites.csv")
TRAFFIC_FILE = os.path.join(FIG1_SOURCE_DIR, "road_network_traffic_flow_proxy.csv")

# Optional layers. Leave as None if unavailable.
INDUSTRIAL_SOURCE_FILE: Optional[str] = None
WATER_OR_PORT_FILE: Optional[str] = None

# Output
OUTPUT_DIR = os.path.join(REPO_ROOT, "figures", "main")
OUTPUT_PNG = os.path.join(OUTPUT_DIR, "Fig1_reproduced_from_source_data.png")
OUTPUT_PDF = os.path.join(OUTPUT_DIR, "Fig1_reproduced_from_source_data.pdf")

# Map settings
USE_BASEMAP = True
BASEMAP_ALPHA = 0.72
ZOOM_MARGIN_X = 0.15
ZOOM_MARGIN_TOP = 0.20
ZOOM_MARGIN_BOTTOM = 0.22   # reserved blank region for map legend


# =============================================================================
# 2. GLOBAL STYLE
# =============================================================================

plt.rcParams["font.family"] = "sans-serif"
plt.rcParams["font.sans-serif"] = ["Arial", "Helvetica", "DejaVu Sans"]
plt.rcParams["axes.unicode_minus"] = False
plt.rcParams["mathtext.default"] = "regular"

FS_PANEL = 28
FS_TITLE = 18
FS_SUBTITLE = 14
FS_TEXT = 10
FS_SMALL = 10
FS_TINY = 10

COL_VEH = "#D55E00"
COL_SHIP = "#377EB8"
COL_IND = "#4DAF4A"
COL_BUFFER = "#B5B5B5"
COL_GRID = "#C8C8C8"
COL_LEFT = "#6C7EA6"
COL_CENTRE = "#E95A5A"
COL_RIGHT = "#6FA8DC"
COL_SIDE = "#5C88DA"
COL_MONITOR = "black"
COL_TRAFFIC_SITE = "#D55E00"
COL_ROAD_CMAP = "Greys"


# =============================================================================
# 3. BASIC HELPERS
# =============================================================================

def hide_ax(ax) -> None:
    ax.set_xticks([])
    ax.set_yticks([])
    for s in ax.spines.values():
        s.set_visible(False)

def add_panel_label(ax, letter: str, x: float = 0.00, y: float = 1.00, size: int = FS_PANEL) -> None:
    ax.text(
        x, y, letter,
        transform=ax.transAxes,
        fontsize=size,
        fontweight="bold",
        ha="left",
        va="bottom",
        color="black",
        clip_on=False
    )

def pol2cart(r: float, theta_deg: float) -> Tuple[float, float]:
    theta = math.radians(theta_deg)
    return r * math.cos(theta), r * math.sin(theta)

def draw_receptor(ax, xy=(0.50, 0.20), r=0.030, label=True, fontsize=FS_TINY) -> None:
    ax.add_patch(Circle(xy, r, facecolor="white", edgecolor="black", lw=1.1, zorder=5))
    if label:
        ax.text(xy[0], xy[1] - 0.060, "Receptor", ha="center", va="top", fontsize=fontsize)

def draw_car_icon(ax, xy=(0.2, 0.8), scale=1.0, color=COL_VEH) -> None:
    x, y = xy
    w, h = 0.060 * scale, 0.026 * scale
    ax.add_patch(Rectangle((x - w / 2, y - h / 2), w, h, facecolor=color, edgecolor="none", alpha=0.96))
    ax.add_patch(Rectangle((x - w * 0.22, y + h * 0.02), w * 0.44, h * 0.50,
                           facecolor=color, edgecolor="none", alpha=0.96))
    for dx in (-w * 0.28, w * 0.28):
        ax.add_patch(Circle((x + dx, y - h * 0.58), h * 0.25, facecolor="black", edgecolor="none"))

def draw_ship_icon(ax, xy=(0.2, 0.8), scale=1.0, color=COL_SHIP) -> None:
    x, y = xy
    hull = Polygon(
        [(x - 0.038 * scale, y - 0.011 * scale),
         (x + 0.032 * scale, y - 0.011 * scale),
         (x + 0.018 * scale, y + 0.006 * scale),
         (x - 0.046 * scale, y + 0.006 * scale)],
        closed=True, facecolor=color, edgecolor="none", alpha=0.96
    )
    cabin = Rectangle((x - 0.010 * scale, y + 0.006 * scale), 0.020 * scale, 0.015 * scale,
                      facecolor=color, edgecolor="none", alpha=0.96)
    ax.add_patch(hull)
    ax.add_patch(cabin)

def draw_factory_icon(ax, xy=(0.2, 0.8), scale=1.0, color=COL_IND) -> None:
    x, y = xy
    ax.add_patch(Rectangle((x - 0.036 * scale, y - 0.019 * scale), 0.072 * scale, 0.038 * scale,
                           facecolor=color, edgecolor="none", alpha=0.96))
    ax.add_patch(Rectangle((x + 0.012 * scale, y + 0.000 * scale), 0.011 * scale, 0.038 * scale,
                           facecolor=color, edgecolor="none", alpha=0.96))
    roof = Polygon(
        [(x - 0.036 * scale, y + 0.000 * scale),
         (x - 0.019 * scale, y + 0.014 * scale),
         (x, y + 0.000 * scale),
         (x + 0.019 * scale, y + 0.014 * scale),
         (x + 0.036 * scale, y + 0.000 * scale)],
        closed=False, fill=False, edgecolor=color, lw=1.6
    )
    ax.add_patch(roof)


# =============================================================================
# 4. PANEL A: DIRECT MAP DRAWING
# =============================================================================

def load_monitoring_sites(monitoring_sites_file: str):
    """Load compact public station metadata for panel a."""
    if not GEOPANDAS_AVAILABLE:
        raise ImportError("geopandas is required to draw panel a directly.")

    if not os.path.exists(monitoring_sites_file):
        raise FileNotFoundError(f"MONITORING_SITES_FILE does not exist: {monitoring_sites_file}")

    df = pd.read_csv(monitoring_sites_file, encoding="utf-8-sig")
    required = ["Station", "Latitude", "Longitude", "StationType"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"monitoring_sites.csv missing required columns: {missing}")

    df["StationType"] = df["StationType"].fillna("Unknown")

    return gpd.GeoDataFrame(
        df,
        geometry=gpd.points_from_xy(df["Longitude"], df["Latitude"]),
        crs="EPSG:4326"
    ).to_crs(epsg=3857)


def load_traffic_network(traffic_file: str):
    if not GEOPANDAS_AVAILABLE:
        return None
    if not os.path.exists(traffic_file):
        print(f"WARNING: TRAFFIC_FILE does not exist: {traffic_file}")
        return None

    df = pd.read_csv(traffic_file, encoding="utf-8-sig")
    required = ["longitude_start", "latitude_start", "longitude_end", "latitude_end", "avg_total_volume_bpr"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        print(f"WARNING: traffic file missing required columns: {missing}")
        return None

    geometry = [
        LineString([(row.longitude_start, row.latitude_start), (row.longitude_end, row.latitude_end)])
        for row in df.itertuples()
    ]
    gdf = gpd.GeoDataFrame(df, geometry=geometry, crs="EPSG:4326").to_crs(epsg=3857)

    max_val = gdf["avg_total_volume_bpr"].max()
    if pd.isna(max_val) or max_val <= 0:
        gdf["lw"] = 0.30
    else:
        gdf["lw"] = (
            np.log10(gdf["avg_total_volume_bpr"].clip(lower=0) + 1)
            / np.log10(max_val + 1)
        ) * 1.85 + 0.08

    return gdf

def add_basemap(ax) -> None:
    if not USE_BASEMAP:
        return
    try:
        import contextily as ctx
        for attempt in range(2):
            try:
                ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron,
                                alpha=BASEMAP_ALPHA, zorder=0)
                return
            except Exception as exc:
                if attempt == 1:
                    print(f"WARNING: basemap skipped: {exc}")
                else:
                    time.sleep(1.5)
    except Exception as exc:
        print(f"WARNING: contextily not available; basemap skipped: {exc}")

def set_map_extent_with_reserved_bottom(ax, sites) -> None:
    xmin, ymin, xmax, ymax = sites.total_bounds
    xrange = xmax - xmin
    yrange = ymax - ymin
    ax.set_xlim(xmin - xrange * ZOOM_MARGIN_X, xmax + xrange * ZOOM_MARGIN_X)
    ax.set_ylim(ymin - yrange * ZOOM_MARGIN_BOTTOM, ymax + yrange * ZOOM_MARGIN_TOP)

def draw_panel_a(ax) -> None:
    hide_ax(ax)
    ax.set_aspect("equal")
    ax.axis("off")

    add_panel_label(ax, "a", x=-0.075, y=1.042)
    ax.text(0.0, 1.03, "Shanghai source setting",
            transform=ax.transAxes, fontsize=FS_TITLE, fontweight="bold",
            ha="left", va="bottom", clip_on=False)

    try:
        sites = load_monitoring_sites(MONITORING_SITES_FILE)
        traffic = load_traffic_network(TRAFFIC_FILE)
    except Exception as exc:
        ax.text(0.5, 0.5, f"Panel a data-loading error:\n{exc}",
                ha="center", va="center", fontsize=10)
        return

    set_map_extent_with_reserved_bottom(ax, sites)
    add_basemap(ax)

    if traffic is not None and not traffic.empty:
        max_vol = traffic["avg_total_volume_bpr"].max()
        min_vol = max(float(traffic["avg_total_volume_bpr"].min()), 1e-6)
        norm = mcolors.LogNorm(vmin=max(min_vol, 1), vmax=max(max_vol, min_vol + 1))
        traffic.plot(
            ax=ax,
            column="avg_total_volume_bpr",
            cmap=COL_ROAD_CMAP,
            norm=norm,
            linewidth=traffic["lw"],
            alpha=0.40,
            zorder=2
        )

        sm = plt.cm.ScalarMappable(cmap=COL_ROAD_CMAP, norm=norm)
        sm._A = []
        cax = ax.inset_axes([0.58, 0.895, 0.29, 0.016])
        cbar = plt.colorbar(sm, cax=cax, orientation="horizontal")
        cbar.set_label("Traffic-flow proxy", fontsize=11, fontweight="bold", labelpad=5)
        cbar.ax.tick_params(labelsize=10, length=2.0)
        cax.xaxis.set_ticks_position("top")
        cax.xaxis.set_label_position("top")

    is_traffic_station = sites["StationType"].astype(str).str.contains("交通", case=False, na=False)

    if (~is_traffic_station).any():
        sites.loc[~is_traffic_station].plot(
            ax=ax, marker="o", color=COL_MONITOR,
            edgecolor="white", linewidth=0.9, markersize=34,
            alpha=0.98, zorder=10
        )
    if is_traffic_station.any():
        sites.loc[is_traffic_station].plot(
            ax=ax, marker="P", color=COL_TRAFFIC_SITE,
            edgecolor="white", linewidth=0.9, markersize=56,
            alpha=0.98, zorder=11
        )

    # North arrow
    ax.text(0.925, 0.835, "N", transform=ax.transAxes, fontsize=11,
            fontweight="bold", ha="center", va="bottom")
    ax.annotate(
        "",
        xy=(0.925, 0.823),
        xytext=(0.925, 0.770),
        xycoords=ax.transAxes,
        arrowprops=dict(arrowstyle="-|>", lw=1.3, color="black"),
        zorder=30
    )

    # Legend placed in the reserved bottom blank area, not over the road network.
    handles = [
        mlines.Line2D([0], [0], marker="o", linestyle="None",
                      markerfacecolor=COL_MONITOR, markeredgecolor="white",
                      markeredgewidth=0.9, markersize=6.2, label="Monitoring site"),
        mlines.Line2D([0], [0], marker="P", linestyle="None",
                      markerfacecolor=COL_TRAFFIC_SITE, markeredgecolor="white",
                      markeredgewidth=0.9, markersize=7.0, label="Traffic-oriented site"),
        mlines.Line2D([0], [0], color="0.35", lw=1.5, label="Road network / traffic-flow proxy"),
    ]
    leg = ax.legend(
        handles=handles,
        loc="lower left",
        bbox_to_anchor=(0.045, 0.035),
        frameon=True,
        framealpha=0.86,
        facecolor="white",
        edgecolor="0.82",
        fontsize=10,
        title="Map layers",
        title_fontsize=11,
        borderpad=0.50,
        handlelength=1.6
    )
    plt.setp(leg.get_title(), fontweight="bold")


# =============================================================================
# 5. PANEL B
# =============================================================================

def draw_single_fixed_buffer(ax, center=(0.25, 0.47), radius=0.165) -> None:
    cx, cy = center
    ax.add_patch(Circle((cx, cy), radius, facecolor="none", edgecolor=COL_BUFFER, lw=1.6))
    draw_receptor(ax, (cx, cy), r=0.026, label=True, fontsize=FS_TINY)

    # Dashed radius axis with a question mark, indicating uncertain buffer radius.
    radius_angle = 315  # degree; 0 = right, 90 = up

    x0, y0 = pol2cart(radius * 0.18, radius_angle)
    x1, y1 = pol2cart(radius * 0.98, radius_angle)

    ax.plot(
        [cx + x0, cx + x1],
        [cy + y0, cy + y1],
        linestyle=(0, (3, 2)),
        color="0.35",
        lw=1.2,
        zorder=6
    )

    xq, yq = pol2cart(radius * 0.64, radius_angle)
    ax.text(
        cx + xq, cy + yq, "?",
        fontsize=18,
        fontweight="bold",
        ha="center",
        va="center",
        color="0.25",
        zorder=7
    )

    # multiple source icons inside / near the same ambiguous buffer
    draw_car_icon(ax, (cx - 0.010, cy + 0.055), scale=0.78)
    draw_ship_icon(ax, (cx + 0.120, cy + 0.105), scale=0.78)
    draw_factory_icon(ax, (cx - 0.125, cy + 0.110), scale=0.78)

def draw_panel_b(ax) -> None:
    hide_ax(ax)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    add_panel_label(ax, "b", x=0.00, y=0.93)

    ax.text(0.05, 0.965,
            "From fixed-radius buffers to source-specific spatial footprints",
            fontsize=FS_TITLE, fontweight="bold", ha="left", va="top")

    ax.text(0.25, 0.83, "Single fixed-radius buffer",
            fontsize=FS_SUBTITLE, fontweight="bold", ha="center", va="center")
    draw_single_fixed_buffer(ax, center=(0.25, 0.47), radius=0.165)
    ax.text(0.25, 0.190, "One radius is imposed\non heterogeneous sources",
            fontsize=FS_SMALL, ha="center", va="center")

    # only micro-adjust the arrow position relative to v4
    ax.add_patch(FancyArrowPatch((0.44-0.01, 0.47), (0.535-0.03, 0.47), arrowstyle="-|>",
                                 mutation_scale=16, lw=1.6, color="0.35"))
    ax.text(0.487-0.02, 0.535, "shift", fontsize=FS_SMALL, fontweight="bold",
            ha="center", va="center", color="0.30")

    ax.text(0.76, 0.83, "Source-specific spatial footprints",
            fontsize=FS_SUBTITLE, fontweight="bold", ha="center", va="center")

    cx2, cy = 0.76, 0.47

    # Scale factor for the right-hand footprint diagram.
    # Smaller value = smaller overall radial extent.
    s = 0.95

    for r in [0.095 * s, 0.170 * s, 0.245 * s]:
        ax.add_patch(Circle((cx2, cy), r, facecolor="none", edgecolor=COL_BUFFER, lw=1.1, alpha=0.70))
    draw_receptor(ax, (cx2, cy), r=0.026, label=True, fontsize=FS_TINY)

    ax.add_patch(Wedge((cx2, cy), 0.110 * s, 62, 118, width=0.068 * s,
                       facecolor=COL_VEH, edgecolor="none", alpha=0.86))
    draw_car_icon(ax, (cx2, cy + 0.192 * s), scale=0.70, color=COL_VEH)
    ax.text(cx2, cy + 0.255 * s, "Vehicle\nnear-field",
            fontsize=FS_TINY, ha="center", va="center", color=COL_VEH, fontweight="bold")

    ax.add_patch(Wedge((cx2, cy), 0.238 * s, 6, 45, width=0.140 * s,
                       facecolor=COL_SHIP, edgecolor="none", alpha=0.68))
    draw_ship_icon(ax, (cx2 + 0.176 * s, cy + 0.160 * s), scale=0.72, color=COL_SHIP)
    ax.text(cx2 + 0.176 * s, cy + 0.230 * s, "Shipping\nkilometre-scale",
            fontsize=FS_TINY, ha="center", va="center", color=COL_SHIP, fontweight="bold")

    ax.add_patch(Wedge((cx2, cy), 0.262 * s, 137, 175, width=0.155 * s,
                       facecolor=COL_IND, edgecolor="none", alpha=0.70))
    draw_factory_icon(ax, (cx2 - 0.190 * s, cy + 0.185 * s), scale=0.72, color=COL_IND)
    ax.text(cx2 - 0.205 * s, cy + 0.255 * s, "Industrial\nbroader-scale",
            fontsize=FS_TINY, ha="center", va="center", color=COL_IND, fontweight="bold")

    ax.text(0.76, 0.190, "Footprint scale and direction\nvary by source type",
            fontsize=FS_SMALL, ha="center", va="center")


# =============================================================================
# 6. PANEL C
# =============================================================================

# Panel C is intentionally drawn as TWO clear sub-figures:
#   left  = initial upwind 3 × 7 sector-grid: three 60° sectors × seven distance bands
#   right = reduced 2 × 7 representation: centre upwind sector + aggregated side sector
# The two sub-figures are placed in inset axes so that labels, arrows and the
# distance-band legend do not overlap the sector geometry.

def _setup_sector_inset(ax) -> None:
    hide_ax(ax)
    ax.set_xlim(-1.08, 1.08)
    ax.set_ylim(-0.23, 1.08)
    ax.set_aspect("equal", adjustable="box")


def _draw_sector_grid_core(
    ax,
    *,
    final: bool = False,
    show_wind_arrow: bool = False,
    receptor_label: bool = True,
) -> None:
    """Draw an upper-half wind-sensitive sector grid inside an inset axis."""
    _setup_sector_inset(ax)

    # Seven distance bands; the first small radius is kept for the receptor mask.
    radii = np.array([0.09, 0.17, 0.27, 0.39, 0.53, 0.67, 0.82, 0.96])

    # Main filled cells. The two lateral 60° sectors use the same colour in the
    # final representation to indicate aggregation into one side-sector group.
    for r0, r1 in zip(radii[:-1], radii[1:]):
        if final:
            lateral_alpha = 0.52
            centre_alpha = 0.74
            cells = [
                (120, 180, COL_SIDE, lateral_alpha),
                (60, 120, COL_CENTRE, centre_alpha),
                (0, 60, COL_SIDE, lateral_alpha),
            ]
        else:
            left_alpha = 0.50
            centre_alpha = 0.74
            right_alpha = 0.50
            cells = [
                (120, 180, COL_LEFT, left_alpha),
                (60, 120, COL_CENTRE, centre_alpha),
                (0, 60, COL_RIGHT, right_alpha),
            ]
        for theta1, theta2, colour, alpha in cells:
            ax.add_patch(Wedge(
                (0, 0), r1, theta1, theta2, width=r1-r0,
                facecolor=colour, edgecolor="white", lw=0.85,
                alpha=alpha, zorder=2
            ))

    # External grid outlines and radial separators, kept subtle for Nature-style clarity.
    for r in radii[1:]:
        ax.add_patch(Arc((0, 0), width=2*r, height=2*r, theta1=0, theta2=180,
                         color="white", lw=0.60, alpha=0.82, zorder=3))
        ax.add_patch(Arc((0, 0), width=2*r, height=2*r, theta1=0, theta2=180,
                         color=COL_GRID, lw=0.32, alpha=0.70, zorder=4))

    for angle in [0, 60, 120, 180]:
        x, y = pol2cart(radii[-1], angle)
        ax.plot([0, x], [0, y], color="white", lw=0.85, alpha=0.75, zorder=4)

    # Baseline and receptor.
    ax.plot([-radii[-1], radii[-1]], [0, 0], color=COL_GRID, lw=0.75, zorder=5)
    ax.add_patch(Circle((0, 0), 0.055, facecolor="white", edgecolor="black", lw=1.0, zorder=8))
    if receptor_label:
        ax.text(0, -0.062, "Receptor", fontsize=FS_TINY, ha="center", va="top", zorder=9)

    # Text labels are placed well inside sectors and outlined to preserve readability.
    stroke = [pe.withStroke(linewidth=2.6, foreground="white")]
    if final:
        ax.text(0, 0.56, "Centre\nupwind\nsector",
                fontsize=FS_TINY + 0.6, fontweight="bold", ha="center", va="center",
                path_effects=stroke, zorder=10)
        ax.text(-0.55, 0.36, "Merged\nside\nsector",
                fontsize=FS_TINY + 0.4, fontweight="bold", ha="center", va="center",
                path_effects=stroke, zorder=10)
        ax.text(0.55, 0.36, "Merged\nside\nsector",
                fontsize=FS_TINY + 0.4, fontweight="bold", ha="center", va="center",
                path_effects=stroke, zorder=10)
    else:
        ax.text(0, 0.56, "Centre sector\n(60° × 7)",
                fontsize=FS_TINY + 0.5, fontweight="bold", ha="center", va="center",
                path_effects=stroke, zorder=10)
        ax.text(-0.56, 0.36, "Left sector\n(60° × 7)",
                fontsize=FS_TINY + 0.25, fontweight="bold", ha="center", va="center",
                path_effects=stroke, zorder=10)
        ax.text(0.56, 0.36, "Right sector\n(60° × 7)",
                fontsize=FS_TINY + 0.25, fontweight="bold", ha="center", va="center",
                path_effects=stroke, zorder=10)

    if show_wind_arrow:
        ax.add_patch(FancyArrowPatch((0, -0.220), (0, -0.100),
                                     arrowstyle="-|>", mutation_scale=13,
                                     lw=1.25, color="black", zorder=10))
        ax.text(0.14, -0.195, "Wind direction", fontsize=FS_TINY,
                ha="left", va="center", zorder=10)


def draw_initial_3x7_sector_grid(ax) -> None:
    _draw_sector_grid_core(ax, final=False, show_wind_arrow=False, receptor_label=False)


def draw_final_2x7_sector_grid(ax) -> None:
    _draw_sector_grid_core(ax, final=True, show_wind_arrow=False, receptor_label=True)


def draw_panel_c(ax) -> None:
    hide_ax(ax)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    add_panel_label(ax, "c", x=0.00, y=0.93)

    ax.text(0.05, 0.965, "Wind-sensitive 2 × 7 sector-grid",
            fontsize=FS_TITLE, fontweight="bold", ha="left", va="top")

    # Sub-panel titles.
    ax.text(0.225, 0.800, "Initial 3 × 7 sector-grid",
            fontsize=FS_SUBTITLE, fontweight="bold", ha="center", va="center")
    ax.text(0.670, 0.800, "Final 2 × 7 representation",
            fontsize=FS_SUBTITLE, fontweight="bold", ha="center", va="center")

    # Draw the two sector figures in their own inset axes to avoid all overlap.
    # left_ax = ax.inset_axes([0.065, 0.265, 0.340, 0.535])
    # right_ax = ax.inset_axes([0.555, 0.235, 0.310, 0.570])
    # left_ax = ax.inset_axes([0.065, 0.205, 0.340, 0.565])
    # right_ax = ax.inset_axes([0.555, 0.195, 0.310, 0.590])
    left_ax = ax.inset_axes([0.065, 0.170, 0.340, 0.565])
    right_ax = ax.inset_axes([0.510, 0.160, 0.310, 0.590])
    draw_initial_3x7_sector_grid(left_ax)
    draw_final_2x7_sector_grid(right_ax)

    ax.add_patch(FancyArrowPatch(
        (0.060, 0.500), (0.060, 0.665),
        arrowstyle="simple",
        mutation_scale=28,
        fc="black",
        ec="black",
        alpha=0.95,
        zorder=40,
        clip_on=False
    ))

    ax.text(
        0.085, 0.585, "Wind\ndirection",
        fontsize=FS_TINY + 0.35,
        ha="left",
        va="center",
        fontweight="bold",
        zorder=40,
        clip_on=False
    )

    # # Bottom annotations under the two figures.
    # ax.text(0.255, 0.205, "3 sectors × 7 distance bands",
    #         fontsize=FS_SMALL, fontweight="bold", ha="center", va="center")
    # ax.text(0.690, 0.085, "2 sectors × 7 distance bands = 14 spatial cells",
    #         fontsize=FS_SMALL, fontweight="bold", ha="center", va="center")

    # Aggregation arrow between the two figures. It is deliberately separated
    # from sector labels and the right-hand distance legend.
    ax.add_patch(FancyArrowPatch((0.385, 0.505), (0.515, 0.505),
                                 arrowstyle="-|>", mutation_scale=15,
                                 lw=1.55, color="0.35", zorder=30))
    ax.text(0.450, 0.600, "Merging\nside sectors",
            fontsize=FS_SMALL, fontweight="bold", ha="center", va="center",
            color="0.30", zorder=30, clip_on=False)

    # Distance-band legend, placed outside the final grid with generous spacing.
    ax.text(0.855, 0.80, "Distance bands", fontsize=FS_SUBTITLE, fontweight="bold",
            ha="left", va="top")
    distance_labels = [
        "0–50 m", "50–100 m", "100–200 m", "200–500 m",
        "500–1000 m", "1000–2000 m", "2000–3000 m"
    ]
    y_positions = np.linspace(0.685, 0.285, len(distance_labels))
    for yy, label in zip(y_positions, distance_labels):
        ax.text(0.858, yy, label, fontsize=FS_TINY + 0.15, ha="left", va="center")


# =============================================================================
# 7. PANEL D
# =============================================================================

def draw_box(ax, xy, w, h, text, fc="#F5F5F5", ec="0.55", fontsize=FS_SMALL, bold=False) -> None:
    x, y = xy
    rect = Rectangle((x, y), w, h, facecolor=fc, edgecolor=ec, lw=1.0)
    ax.add_patch(rect)
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center",
            fontsize=fontsize, fontweight=("bold" if bold else "normal"))

def draw_panel_d(ax) -> None:
    hide_ax(ax)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)

    add_panel_label(ax, "d", x=0.00, y=0.93)
    ax.text(0.05, 0.965,
            "From spatial representation to transferable attribution",
            fontsize=FS_TITLE, fontweight="bold", ha="left", va="top")

    y = 0.50
    h = 0.22
    boxes = [
        (0.05, y, 0.19, h, "Monitoring,\nmeteorology\nand urban predictors", "#F8F8F8", "58 monitoring sites"),
        (0.30, y, 0.22, h, "Wind-sensitive,\nsource-aware\nspatial aggregation", "#FFF5F5", "2 sectors × 7 bands"),
        (0.58, y, 0.18, h, "Spatial/temporal\ngeneralisation\n+ SHAP attribution", "#F8F8F8", "model generalisation\nand attribution"),
        (0.82, y, 0.14, h, "Scale-aware\nurban diagnosis", "#F5F9FF", "monitoring, exposure\nand planning"),
    ]

    for x, yy, w, hh, txt, fc, anchor in boxes:
        ec = "#D99999" if "Wind-sensitive" in txt else ("#9DB9E8" if "Scale-aware" in txt else "0.55")
        draw_box(ax, (x, yy), w, hh, txt, fc=fc, ec=ec, fontsize=FS_TINY+0.2, bold=True)
        ax.text(x + w/2, yy - 0.12, anchor, fontsize=FS_TINY, ha="center", va="center")

    for x1, x2 in [(0.24, 0.30), (0.52, 0.58), (0.76, 0.82)]:
        ax.add_patch(FancyArrowPatch((x1, y + h/2), (x2, y + h/2),
                                     arrowstyle="-|>", mutation_scale=13,
                                     lw=1.4, color="0.35"))

    ax.text(0.05, 0.25,
            "Outputs support source-specific footprint identification and transferable diagnosis across dense urban micro-environments.",
            fontsize=FS_TEXT, ha="left", va="center")


# =============================================================================
# 8. MAIN COMPOSITOR
# =============================================================================

def main() -> None:
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    fig = plt.figure(figsize=(16.8, 11.8), dpi=300)
    gs = GridSpec(
        nrows=3,
        ncols=2,
        figure=fig,
        width_ratios=[0.94, 1.36],
        height_ratios=[0.94, 0.86, 0.78],
        left=0.035,
        right=0.985,
        top=0.970,
        bottom=0.035,
        wspace=0.04,
        hspace=-0.05
    )

    ax_a = fig.add_subplot(gs[:, 0])
    draw_panel_a(ax_a)

    ax_b = fig.add_subplot(gs[0, 1])
    draw_panel_b(ax_b)

    ax_c = fig.add_subplot(gs[1, 1])
    draw_panel_c(ax_c)

    ax_d = fig.add_subplot(gs[2, 1])
    draw_panel_d(ax_d)

    fig.savefig(OUTPUT_PNG, dpi=300, facecolor="white")
    fig.savefig(OUTPUT_PDF, dpi=300, facecolor="white")
    plt.close(fig)

    print("Saved:")
    print(OUTPUT_PNG)
    print(OUTPUT_PDF)

if __name__ == "__main__":
    main()
